"""Architecture-aware recipes — catalog + gates + model cards + personal book."""

from anvil.recipes.book import (
    BookRecipe,
    RecipeBook,
    default_book_root,
    export_org_pack,
    install_org_pack,
    promote_from_run,
)
from anvil.recipes.catalog import (
    GateLevel,
    GateResult,
    RecipeSpec,
    default_recipe_id_for_shape,
    gate_recipe,
    get_recipe,
    list_recipes,
    recipes_for_shape,
)
from anvil.recipes.dpo import DPOResult, PreferencePair, run_dpo
from anvil.recipes.meta import (
    MetaEdge,
    MetaRecipe,
    MetaStage,
    example_vlm_ladder,
    get_meta_recipe,
    list_meta_recipes,
    next_stage,
    save_meta_recipe,
)
from anvil.recipes.meta_exec import (
    MetaExecResult,
    StageRunResult,
    run_meta_recipe,
)
from anvil.recipes.model_card import ModelCardFacts, inspect_base_model
from anvil.recipes.profiles import (
    JobPattern,
    ModelShape,
    PatternSpec,
    RecipePlan,
    infer_model_family,
    infer_shape,
    list_patterns,
    plan_recipe,
    suggest_for_model,
)
from anvil.recipes.robot_offline import (
    DEFAULT_ROBOT_BASE,
    RobotOfflineResult,
    run_robot_offline,
    toy_robot_trajectories,
    trajectories_to_robot_examples,
)
from anvil.recipes.vision_rl import (
    VisionRLQueueRecipe,
    VisionRollout,
    run_vision_grpo,
    run_vision_rl_queue,
    toy_vision_rollouts,
)

__all__ = [
    "BookRecipe",
    "DEFAULT_ROBOT_BASE",
    "DPOResult",
    "GateLevel",
    "GateResult",
    "JobPattern",
    "MetaEdge",
    "MetaExecResult",
    "MetaRecipe",
    "MetaStage",
    "ModelCardFacts",
    "ModelShape",
    "PatternSpec",
    "PreferencePair",
    "RecipeBook",
    "RecipePlan",
    "RecipeSpec",
    "RobotOfflineResult",
    "StageRunResult",
    "VisionRLQueueRecipe",
    "VisionRollout",
    "default_book_root",
    "default_recipe_id_for_shape",
    "example_vlm_ladder",
    "export_org_pack",
    "gate_recipe",
    "get_meta_recipe",
    "get_recipe",
    "infer_model_family",
    "infer_shape",
    "inspect_base_model",
    "install_org_pack",
    "list_meta_recipes",
    "list_patterns",
    "list_recipes",
    "next_stage",
    "plan_recipe",
    "promote_from_run",
    "recipes_for_shape",
    "run_dpo",
    "run_meta_recipe",
    "run_robot_offline",
    "run_vision_grpo",
    "run_vision_rl_queue",
    "save_meta_recipe",
    "suggest_for_model",
    "toy_robot_trajectories",
    "toy_vision_rollouts",
    "trajectories_to_robot_examples",
]
